openapi: 3.0.1
info:
  title: Openapi Order
  description: openapi swagger code-gen을 활용한 order 구현
  version: 1.0.0
servers:
  - url: http://localhost:8080
#tags:
#  - name: pending-order

paths:
  /orders/pendingOrder/{id}:
    get:
      tags:
        - pending-order
      summary: get pending order by Id
      operationId: getPendingOrderById
      parameters:
        - name: id
          description: pending order id
          schema:
            type: integer
            format: int64
          in: path
          required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PendingOrderResponse'
    put:
      tags:
        - pending-order
      summary: update pending order
      operationId: updatePendingOrder
      parameters:
        - name: id
          description: pending order id
          schema:
            type: integer
            format: int64
          in: path
          required: true
      requestBody:
        description: pending order request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PendingOrderRequest'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PendingOrderResponse'
  /orders/pendingOrder:
    post:
      tags:
        - pending-order
      summary: create pending order
      operationId: createPendingOrder
      requestBody:
        description: pending order request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PendingOrderRequest'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PendingOrderResponse'
    get:
      tags:
        - pending-order
      summary: get all pending orders
      operationId: getAllPendingOrders
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/PendingOrderResponse'

components:
  schemas:
    PendingOrderRequest:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
    PendingOrderResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        productId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32